Update readme and add list animation example
arfc/pres pull request #7
Opened 2022-03-28 20:41 UTC by nsryan2

This PR adds information about using the template (almost exactly the same as the report template), and using the animation feature for bulleted lists as requested in #6.

2022-03-30 21:51 UTC, smpark7 requested changes
I only have minor comments. Otherwise it looks great and thanks for introducing these improvements!

2022-03-30 21:51 UTC, smpark7 commented on README.md
> +This repository is intended as a template to standardize and ease the implimentation
```suggestion
This repository is intended as a template to standardize and ease the implementation 
```

2022-03-30 21:51 UTC, smpark7 commented on README.md
> +http://arfc.npre.illinois.edu/manual/guides/writing/presentation
Do you mean to say "presentation" instead of "report" here?

2022-03-30 21:51 UTC, smpark7 commented on conclusion.tex
> +        you can animate bulletted lists, for more information about
```suggestion
        you can animate bulleted lists, for more information about
```

2022-03-30 23:32 UTC, nsryan2 commented on README.md
> +http://arfc.npre.illinois.edu/manual/guides/writing/presentation
```suggestion
# ARFC Report Manual
For ARFC specific guidelines for making a presentation, read the specifics at
http://arfc.npre.illinois.edu/manual/guides/writing/presentation
```

2022-03-30 23:33 UTC, nsryan2 commented
Thanks for the feedback, should be all good to go now!

2022-03-31 00:47 UTC, smpark7 approved these changes

2022-03-31 00:48 UTC, merged